package com.steve.mybatis.dao;

import com.steve.mybatis.domain.SysConfig;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Jul 04 16:30:15 CST 2020
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Jul 04 16:30:15 CST 2020
     */
    int insertSelective(SysConfig record);
}